---
title: Software
description: Installs preferred software 
privilege: TrustedInstaller
actions:

  # https://github.com/meetrevision/playbook/issues/81
  # - !status: {status: 'Updating Winget'}
  # - !powerShell:
  #   weight: 50
  #   runas: currentUserElevated
  #   wait: true
  #   exeDir: true
  #   command: '.\UPDATE-APPX.ps1'

  - !status: {status: 'Installing Brave', option: "browser-brave"}
  - !download: 
    option: "browser-brave"
    url: 'https://github.com/brave/brave-browser/releases/latest/download/BraveBrowserStandaloneSetup.exe'
    destination: "BraveBrowserStandaloneSetup.exe"
    cpuArch: X64
    package: 'brave'
  - !run:
    exeDir: true
    exe: "BraveBrowserStandaloneSetup.exe"
    args: "/silent /install"
    cpuArch: X64
    weight: 150
    option: "browser-brave"

  - !download: 
    option: "browser-brave"
    url: 'https://github.com/brave/brave-browser/releases/latest/download/BraveBrowserStandaloneSetup.exe'
    destination: "BraveBrowserStandaloneSetupArm64.exe"
    cpuArch: Arm64
    package: 'brave'
  - !run:
    exeDir: true
    exe: "BraveBrowserStandaloneSetupArm64.exe"
    args: "/silent /install"
    cpuArch: Arm64
    weight: 150
    option: "browser-brave"

  - !status: {status: 'Configuring Brave', option: "browser-brave"}
  - !cmd:
    exeDir: true
    command: 'robocopy "BraveSoftware" "%ProgramFiles%\BraveSoftware" /E /IM /IT /NP & robocopy "BraveSoftware" "%localappdata%\BraveSoftware" /E /IM /IT /NP'
    ignoreErrors: true
    weight: 20
    option: "browser-brave"

  # Firefox
  - !status: {status: 'Installing Firefox', option: "browser-firefox"}
  - !download:
    option: "browser-firefox"
    url: 'https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US'
    destination: "FirefoxSetup.exe"
    cpuArch: X64
  - !run:
    exeDir: true
    exe: "FirefoxSetup.exe"
    args: "/S"
    weight: 150
    option: "browser-firefox"

  # OBS Studio
  - !status: {status: 'Installing OBS Studio', option: "streaming-obs"}
  - !download:
    option: "streaming-obs"
    url: 'https://cdn.obsproject.com/downloads/OBS-Studio-Full-Installer-x64.exe'
    destination: "OBS-Studio-Setup.exe"
    cpuArch: X64
  - !run:
    exeDir: true
    exe: "OBS-Studio-Setup.exe"
    args: "/S"
    weight: 150
    option: "streaming-obs"

  # StreamElements GroundControl
  - !status: {status: 'Installing StreamElements GroundControl', option: "streaming-groundcontrol"}
  - !download:
    option: "streaming-groundcontrol"
    url: 'https://groundcontrol.streamelements.com/download/windows'
    destination: "GroundControl-Setup.exe"
    overwrite: true
  - !run:
    exeDir: true
    exe: "GroundControl-Setup.exe"
    args: "/S"
    weight: 150
    option: "streaming-groundcontrol"

  # Discord
  - !status: {status: 'Installing Discord', option: "streaming-discord"}
  - !download:
    option: "streaming-discord"
    url: 'https://discord.com/api/download?platform=win'
    destination: "DiscordSetup.exe"
    cpuArch: X64
  - !run:
    exeDir: true
    exe: "DiscordSetup.exe"
    args: "/s"
    weight: 150
    option: "streaming-discord"

  # Voicemeeter Banana
  - !status: {status: 'Installing Voicemeeter Banana', option: "streaming-voicemeeter"}
  - !download:
    option: "streaming-voicemeeter"
    url: 'https://vb-audio.com/Voicemeeter/VoicemeeterBanana_Setup.exe'
    destination: "VoicemeeterBananaSetup.exe"
    cpuArch: X64
  - !run:
    exeDir: true
    exe: "VoicemeeterBananaSetup.exe"
    args: "/S"
    weight: 150
    option: "streaming-voicemeeter"