---
title: Initialization
description: Copies EB folders/files, and configures some initial settings
privilege: TrustedInstaller
actions:
  
  - !writeStatus: {status: "Initializing"}

  # Prevent annoying notifications during deployment
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance'
    value: 'Enabled'
    type: REG_DWORD
    data: '0'

  - !cmd:
    exeDir: true
    command: 'robocopy "Licenses" "%SystemDrive%\Licenses" /E /PURGE /IM /IT /NP'
    ignoreErrors: true
    weight: 30
    
  - !cmd:
    exeDir: true
    command: 'copy /y "hosts" "%WINDIR%\System32\drivers\etc\hosts"'
    weight: 20

  # Necessary to clean DNS Cache after modifying hosts
  - !cmd:
    command: 'ipconfig /flushdns'

  - !writeStatus: {status: "Installing VCRedist"}
  - !download: 
    url: 'https://aka.ms/vs/17/release/vc_redist.x64.exe'
    destination: "vc_redist.x64.exe"
    overwrite: true
  - !run:
    exeDir: true
    exe: "vc_redist.x64.exe"
    args: '/quiet /norestart'

  - !writeStatus: {status: 'Installing EB Tool'}
  - !run:
    exeDir: true
    exe: "eb-tool-Setup.exe"
    args: '/VERYSILENT /TASKS="desktopicon"'
    weight: 150

  - !writeStatus: {status: "Updating EB Tool binaries"}
  - !cmd:
    exeDir: true
    command: 'copy /y "eb-tool.exe" "%ProgramFiles%\EB Tool\eb-tool.exe"'
    ignoreErrors: true
  - !cmd:
    exeDir: true
    command: 'copy /y "eb-tool-cli.exe" "%ProgramFiles%\EB Tool\eb-tool-cli.exe"'
    ignoreErrors: true

  - !writeStatus: {status: "Configuring a power plan"}
  - !run:
    path: "%ProgramFiles%\\EB Tool"
    exe: "eb-tool.exe"
    args: "tweaks performance powerplan enable"
    wait: true
    runas: currentUserElevated

  - !writeStatus: {status: "Optimizing PowerShell"}
  - !run:
    exeDir: true
    exe: "PowerShell"
    args: '-NoP -ExecutionPolicy Bypass -File ngen.ps1'
    weight: 100