---
title: eb-static-edition
description: eb-static-edition
privilege: TrustedInstaller
actions:

  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubManufacturer', type: REG_SZ, data: 'EB'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubstring', type: REG_SZ, data: 'Revision'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value: 'EditionSubVersion', type: REG_SZ, data: 'EBOS'}


  # === Causes Network Sharing/Computer Name issues
  # - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\ComputerName\ComputerName', value: 'ComputerName', type: REG_SZ, data: 'EB-PC'}
  # - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\ComputerName\ActiveComputerName', value: 'ComputerName', type: REG_SZ, data: 'EB-PC'}